### ISSUE TITLE
Flow improvement

### ISSUE THREAD

**Issue by scoavoux** [scoavoux/PandocTools#10]
+ ~~Autopair `*` and `_` (emphasis and bold).~~
+ ~~Automatically continue blockquotes (after a return, begin newline with `>`)~~
+ Allow one empty blockquote line
+ ~~Automatically continue lists (after return, begin newline with the same symbol as current line if `+ - *`, or with `n + 1` if `n.` `n)`~~

**Comment by scoavoux** [comment]
commit 2b87e80 adds the autopairing

**Comment by theyate** [comment]
Commit  	d1b888b adds the automatical continaution of blockquotes and lists.
The auto added text can be deleted by typing [enter] (we assume that this signals the end of a list), or by typing [delete].

Supported

     > test
     >

     1. test
     2.

     1) test
     2) 

     #) test
     #) 

     * test
     *

     + test
     + 

     - test
     - 
Not supported

     (1)

**Comment by scoavoux** [comment]
We still need to find a way to allow one empty blockquote line, ie. delete the last empty lines after two new lines (and not one).

    > some text
    > 
    > next paragraph
