### ISSUE TITLE
support for pandoc-crossref

### ISSUE THREAD

**Issue by scoavoux** [scoavoux/PandocTools#16]
pandoc-crossref adds table and figure caption <https://github.com/lierdakil/pandoc-crossref>

Add : 

+ syntax highlighting for attributes and for references to tables and figures
+ command to find all references in the document and insert them at a given point

**Comment by scoavoux** [comment]
commit ad549bb adds the function pandoc_crossref_cite that parses the current document for cross-references and inserts references from a search in the drop-down panel.

todo next :

+ add syntax
+ add a pre-completion function 
+ add support for equations and codeblocks

**Comment by XaraB** [comment]
Haha, t'as une deadline, c'est ça ?
