### ISSUE TITLE
trying to get out of autolist sends to next line

### ISSUE THREAD

**Issue by scoavoux** [scoavoux/PandocTools#17]
In a list, enter goes to next line which is an automatic continuation of the list, and enter gets out of the list. If I press it at the end of the line, everything's fine. But if there is some text after the caret when I press it, then the `+|*|-` sign is removed, the text that follows stays on that line, and the caret goes to the next one.

This is not expected behavior. In such a case, what should happen is that the `+|*|-` sign is removed, the rest of the line is send to next line, with the caret at the beginning.

Reproducing : (| is the caret)

    + list element 1
    + list element 2
    + |sometext

On enter becomes :

    + list element 1
    + list element 2
    sometext
    |

Should become :

    + list element 1
    + list element 2
    
    |sometext

**Comment by theyate** [comment]
This should be fixed. Will close when you confirm.

**Comment by scoavoux** [comment]
@theyate thanks!
