### ISSUE TITLE
Sublist completion

### ISSUE THREAD

**Issue by theyate** [scoavoux/PandocTools#18]
When typing "\t" after a list bullet, the list bullet should move after the tab (or spaces) to create a sub-list.
Sub-lists should be autocompleted too.

**Comment by theyate** [comment]
Sublist are now autocompleted, but the tab thing isn't resolved yet.

**Comment by theyate** [comment]
Now ("|" as caret): 

    * |<tab>

transforms to :

    <tab>* |

This works for all lists matching : `^( *)([+*-]|\\d+[.)]|#\\.) ?`

**Comment by scoavoux** [comment]
Nested lists do not autocomplete

        + text|<enter>

produces :

        + text
        |

instead of 

        + text
        + |

**Comment by theyate** [comment]
This was an issue for users indenting with tabs, the regex was changed from ( *) at the beginning to (\s*), and the functionality is now operational for both tabs and spaces.
